name: MythicSpawnView
main: doglong.mythicspawnview.libs.Main
plugin: doglong.mythicspawnview.MythicSpawnView
version: 1.0
api-version: 1.12
authors: [ DogLong ]
depend:
  - MythicMobs
  - HolographicDisplays